"use strict";
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "app-v4.js"), "utf8");
const css = fs.readFileSync(path.join(root, "styles-v4.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");

assert.match(app, /path === "\/settings"/);
assert.match(app, /data-action="parse-model-rule"/);
assert.match(app, /data-action="parse-local-rule"/);
assert.match(app, /确认规则并进入检查/);
assert.match(app, /parsed \? .*ops-rule-summary/s);
assert.match(app, /<details class="glass-panel technical-details">/);
assert.match(app, /超过（不含）/);
assert.doesNotMatch(app, /data-action="parse-natural-rule"/);
assert.equal((app.match(/button\("确认规则并进入检查"/g) || []).length, 1, "strategy page must expose one primary confirmation button");
assert.match(app, /"confirm-and-save-rule"/);
assert.doesNotMatch(app, /writeStore\([^\n]*modelSettings/i);
assert.match(css, /Operations strategy editor and model settings v20/);
assert.match(css, /@media \(max-width: 1040px\)/);
assert.match(html, /styles-v4\.css\?v=20/);
assert.match(html, /app-v4\.js\?v=20/);
assert.match(app, /\/api\/app-state/);
assert.match(app, /\/api\/fact-snapshots\/freeze/);
assert.match(app, /\/api\/ontology\/build/);
assert.match(app, /\/api\/simulations/);
assert.match(app, /PET_BACKEND_MARKER/);
assert.doesNotMatch(app, /function persistWorkflow\(\) \{ writeStore/);
console.log("frontend smoke: 21 assertions passed");
